version: 2

project_name: gha-token

builds:
  - id: gha-token
    main: ./cmd/gha-token
    binary: gha-token
    ldflags:
      - -s -w -X github.com/mumincacao/gha-token/internal/version.Version={{ .Version }}
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: binary
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}.{{ .Version }}.{{ .Os }}.{{ .Arch }}"
    files:
      - gha-token
    builds:
      - gha-token

changelog:
  disable: true

release:
  disable: false
  github:
    owner: mumincacao
    name: gha-token

